In [1]:
import pandas as pd
import numpy as np

In [2]:
#Read training and testing data

training_data = pd.read_excel(r'C:\Python\K Nearest\Titanic_Survival_Train.xls',index_col=0,header=0)
testing_data = pd.read_excel(r'C:\Python\K Nearest\Titanic_Survival_Test.xls',index_col=0,header=0)

In [3]:
print(training_data.shape)
print(testing_data.shape)

(891, 11)
(21, 11)


In [4]:
training_data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [5]:
testing_data.head()

Survived  Pclass  \
PassengerId                     
871                 0       3   
872                 1       1   
873                 0       1   
874                 0       3   
875                 1       2   

                                                         Name     Sex   Age  \
PassengerId                                                                   
871                                         Balkic, Mr. Cerin    male  26.0   
872          Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0   
873                                  Carlsson, Mr. Frans Olof    male  33.0   
874                               Vander Cruyssen, Mr. Victor    male  47.0   
875                     Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0   

             SibSp  Parch     Ticket     Fare        Cabin Embarked  
PassengerId                                                          
871              0      0     349248   7.8958          NaN        S  
872              1      1      11751  52.5542          D35        S  
873              0      0        695   5.0000  B51 B53 B55        S  
874              0      0     345765   9.0000          NaN        S  
875              1      0  P/PP 3381  24.0000          NaN        C

In [6]:
#Feature selection

training_data = training_data[['Name','Pclass','Sex','Age','Survived']]
testing_data = testing_data[['Name','Pclass','Sex','Age','Survived']]

print(training_data.shape)
print(testing_data.shape)

(891, 5)
(21, 5)


In [7]:
training_data.dtypes


Name         object
Pclass        int64
Sex          object
Age         float64
Survived      int64
dtype: object

In [8]:
testing_data.dtypes

Name         object
Pclass        int64
Sex          object
Age         float64
Survived      int64
dtype: object

In [9]:
#finding the missing values

print(training_data.isnull().sum())
print(testing_data.isnull().sum())

Name          0
Pclass        0
Sex           0
Age         177
Survived      0
dtype: int64
Name        0
Pclass      0
Sex         0
Age         2
Survived    0
dtype: int64


In [10]:
training_data['Age'].fillna(int(training_data['Age'].mean()),inplace=True)

In [11]:
testing_data['Age'].fillna(int(testing_data['Age'].mean()),inplace=True)

In [12]:
print(training_data.isnull().sum())
print(testing_data.isnull().sum())

Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64
Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64


In [13]:
#transforming categorical data to numerical

from sklearn import preprocessing

colname=['Sex']

le=preprocessing.LabelEncoder()    #LabelEncoder()  == technique of transformation == object to int/float

for x in colname:
    training_data[x]=le.fit_transform(training_data[x])
    testing_data[x]=le.fit_transform(testing_data[x])

In [14]:
training_data.dtypes

Name         object
Pclass        int64
Sex           int32
Age         float64
Survived      int64
dtype: object

In [15]:
testing_data.dtypes

Name         object
Pclass        int64
Sex           int32
Age         float64
Survived      int64
dtype: object

In [16]:
print(training_data.head())

                                                          Name  Pclass  Sex  \
PassengerId                                                                   
1                                      Braund, Mr. Owen Harris       3    1   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...       1    0   
3                                       Heikkinen, Miss. Laina       3    0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)       1    0   
5                                     Allen, Mr. William Henry       3    1   

              Age  Survived  
PassengerId                  
1            22.0         0  
2            38.0         1  
3            26.0         1  
4            35.0         1  
5            35.0         0  


In [17]:
print(testing_data.head())

                                                         Name  Pclass  Sex  \
PassengerId                                                                  
871                                         Balkic, Mr. Cerin       3    1   
872          Beckwith, Mrs. Richard Leonard (Sallie Monypeny)       1    0   
873                                  Carlsson, Mr. Frans Olof       1    1   
874                               Vander Cruyssen, Mr. Victor       3    1   
875                     Abelson, Mrs. Samuel (Hannah Wizosky)       2    0   

              Age  Survived  
PassengerId                  
871          26.0         0  
872          47.0         1  
873          33.0         0  
874          47.0         0  
875          28.0         1  


In [18]:
#Create X and Y

X_train = training_data.values[:,1:-1]
Y_train = training_data.values[:,-1]

Y_train = Y_train.astype(int)

X_test = testing_data.values[:,1:-1]
Y_test = testing_data.values[:,-1]

Y_test = Y_test.astype(int)


In [19]:
#fitting scaler is only done on training data and only on x
#same scales are applied to both training as well as testing data (transform)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

C:\Users\ALI\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\ALI\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\ALI\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


**Model Building**

In [20]:
#predicting using KNeighbors_Classifier

from sklearn.neighbors import KNeighborsClassifier

model_KNN =KNeighborsClassifier(n_neighbors=5, metric='euclidean')

#fit model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred = model_KNN.predict(X_test)

print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0)]


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")


print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[11  3]
 [ 0  7]]
Classification report: 
              precision    recall  f1-score   support

           0       1.00      0.79      0.88        14
           1       0.70      1.00      0.82         7

   micro avg       0.86      0.86      0.86        21
   macro avg       0.85      0.89      0.85        21
weighted avg       0.90      0.86      0.86        21

Accuracy of the model:  0.8571428571428571


In [22]:

from sklearn.neighbors import KNeighborsClassifier

model_KNN =KNeighborsClassifier(n_neighbors=4, metric='euclidean')
#model_KNN =KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))), metric='euclidean')   ... using sqrt logic


#fit model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred = model_KNN.predict(X_test)

print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (0, 0)]


In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")


print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[14  0]
 [ 0  7]]
Classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00         7

   micro avg       1.00      1.00      1.00        21
   macro avg       1.00      1.00      1.00        21
weighted avg       1.00      1.00      1.00        21

Accuracy of the model:  1.0


In [24]:
#find best suitable value for k to check best accuracy

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

for K in range(1,16):
    model_KNN = KNeighborsClassifier(K,metric="euclidean")
    model_KNN.fit(X_train, Y_train) 
    Y_pred = model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred),"Confusion Matrix" , confusion_matrix(Y_test,Y_pred) , "for K-Value:",K)



Accuracy is  0.8571428571428571 Confusion Matrix [[11  3]
 [ 0  7]] for K-Value: 1
Accuracy is  1.0 Confusion Matrix [[14  0]
 [ 0  7]] for K-Value: 2
Accuracy is  0.9523809523809523 Confusion Matrix [[13  1]
 [ 0  7]] for K-Value: 3
Accuracy is  1.0 Confusion Matrix [[14  0]
 [ 0  7]] for K-Value: 4
Accuracy is  0.8571428571428571 Confusion Matrix [[11  3]
 [ 0  7]] for K-Value: 5
Accuracy is  0.9523809523809523 Confusion Matrix [[13  1]
 [ 0  7]] for K-Value: 6
Accuracy is  0.9047619047619048 Confusion Matrix [[12  2]
 [ 0  7]] for K-Value: 7
Accuracy is  0.9047619047619048 Confusion Matrix [[12  2]
 [ 0  7]] for K-Value: 8
Accuracy is  0.8571428571428571 Confusion Matrix [[11  3]
 [ 0  7]] for K-Value: 9
Accuracy is  0.9523809523809523 Confusion Matrix [[13  1]
 [ 0  7]] for K-Value: 10
Accuracy is  0.9047619047619048 Confusion Matrix [[12  2]
 [ 0  7]] for K-Value: 11
Accuracy is  0.9523809523809523 Confusion Matrix [[13  1]
 [ 0  7]] for K-Value: 12
Accuracy is  0.9047619047619048

In [25]:
#predicting using KNeighbors_Classifier

from sklearn.neighbors import KNeighborsClassifier

#model_KNN =KNeighborsClassifier(n_neighbors=4, metric='manhattan')
model_KNN =KNeighborsClassifier(n_neighbors=4, metric='minkowski')

#fit model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred = model_KNN.predict(X_test)

print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (0, 0)]


In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")


print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[14  0]
 [ 0  7]]
Classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00         7

   micro avg       1.00      1.00      1.00        21
   macro avg       1.00      1.00      1.00        21
weighted avg       1.00      1.00      1.00        21

Accuracy of the model:  1.0


Tuning part can be done by using adjusting different values for k and metric
and aslo selecting different variables