In [3]:
import pandas as pd
import numpy as np


In [4]:
#import data from excel

cars_data=pd.read_csv(r'C:\Python\cars.csv',header=None)
cars_data.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [5]:
cars_data.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_data.head()


buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [6]:
cars_data.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [7]:
cars_df=pd.DataFrame.copy(cars_data)

In [8]:
colname=cars_df.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [9]:
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in colname:
    cars_df[x]=le.fit_transform(cars_df[x])
    

In [10]:
cars_df.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       3      3      0        0         2       1        2
1       3      3      0        0         2       2        2
2       3      3      0        0         2       0        2
3       3      3      0        0         1       1        2
4       3      3      0        0         1       2        2

In [11]:
cars_data.classes.value_counts()

#acc==>0
#good==>1
#unacc==>2
#vgood==>3

unacc    1210
acc       384
good       69
vgood      65
Name: classes, dtype: int64

In [12]:
X=cars_df.values[:,:-1]
Y=cars_df.values[:,-1]
Y=Y.astype(int)

In [13]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X)

X=scaler.transform(X)



C:\Users\ALI\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\ALI\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [14]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [15]:
#Running Decesion Tree Model

from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(random_state=10,min_samples_leaf=5,max_depth=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=10,
            splitter='best')

In [16]:
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print('Classification report')

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print('Accuracy of the model:',acc)

[[ 92   6   4   0]
 [  0  17   2   2]
 [  8   0 363   0]
 [  3   5   0  17]]
Classification report
              precision    recall  f1-score   support

           0       0.89      0.90      0.90       102
           1       0.61      0.81      0.69        21
           2       0.98      0.98      0.98       371
           3       0.89      0.68      0.77        25

   micro avg       0.94      0.94      0.94       519
   macro avg       0.84      0.84      0.84       519
weighted avg       0.95      0.94      0.94       519

Accuracy of the model: 0.9421965317919075


In [18]:
print(list(zip(colname,model_DecisionTree.feature_importances_)))

[('buying', 0.15391565199335028), ('maint', 0.2699990515342031), ('doors', 0.03511651586061642), ('persons', 0.18449221442490638), ('lug_boot', 0.08402440114201538), ('safety', 0.2724521650449083)]


In [19]:
from sklearn import tree
with open('model_DecisionTree.txt','w') as f:
    f=tree.export_graphviz(model_DecisionTree,feature_names=colname[:-1],out_file=f)

In [20]:
from sklearn import svm
classifier=svm.SVC(kernel='rbf',gamma=0.1,C=70)
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print=(list(zip(Y_test,Y_pred)))

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print('Classification report')

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print('Accuracy of the model:',acc)

[[ 99   2   1   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]
Classification report
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       102
           1       0.91      1.00      0.95        21
           2       1.00      1.00      1.00       371
           3       1.00      1.00      1.00        25

   micro avg       0.99      0.99      0.99       519
   macro avg       0.98      0.99      0.98       519
weighted avg       0.99      0.99      0.99       519

Accuracy of the model: 0.9942196531791907


In [22]:
from sklearn.linear_model import  LogisticRegression

classifier=LogisticRegression()

classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)

C:\Users\ALI\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ALI\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print('Classification report')

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print('Accuracy of the model:',acc)

[[ 22   0  80   0]
 [  3   0  18   0]
 [ 30   0 341   0]
 [ 11   0  14   0]]
Classification report
              precision    recall  f1-score   support

           0       0.33      0.22      0.26       102
           1       0.00      0.00      0.00        21
           2       0.75      0.92      0.83       371
           3       0.00      0.00      0.00        25

   micro avg       0.70      0.70      0.70       519
   macro avg       0.27      0.28      0.27       519
weighted avg       0.60      0.70      0.64       519

Accuracy of the model: 0.6994219653179191


C:\Users\ALI\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [24]:
#Running ExtraTreesClassifier model
#prediction using the Bagging_classifier

from sklearn.ensemble import ExtraTreesClassifier

model=ExtraTreesClassifier(50,random_state=10)
#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)

Y_pred=model.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print('Classification report')

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print('Accuracy of the model:',acc)

[[100   0   2   0]
 [  3  18   0   0]
 [  3   0 368   0]
 [  1   2   0  22]]
Classification report
              precision    recall  f1-score   support

           0       0.93      0.98      0.96       102
           1       0.90      0.86      0.88        21
           2       0.99      0.99      0.99       371
           3       1.00      0.88      0.94        25

   micro avg       0.98      0.98      0.98       519
   macro avg       0.96      0.93      0.94       519
weighted avg       0.98      0.98      0.98       519

Accuracy of the model: 0.9788053949903661


In [26]:
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(100,random_state=10)
#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print('Classification report')

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print('Accuracy of the model:',acc)

[[ 99   3   0   0]
 [  1  19   0   1]
 [  2   0 369   0]
 [  2   0   0  23]]
Classification report
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       102
           1       0.86      0.90      0.88        21
           2       1.00      0.99      1.00       371
           3       0.96      0.92      0.94        25

   micro avg       0.98      0.98      0.98       519
   macro avg       0.94      0.95      0.95       519
weighted avg       0.98      0.98      0.98       519

Accuracy of the model: 0.9826589595375722


In [28]:
#prediction using the AdaBoost_Classifier
from sklearn.ensemble import AdaBoostClassifier

model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(),n_estimators=50,random_state=10)
#fit the model on the data and predict the values
model_AdaBoost.fit(X_train,Y_train)

Y_pred=model_AdaBoost.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print('Classification report')

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print('Accuracy of the model:',acc)

[[ 99   2   1   0]
 [  4  17   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
Classification report
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       102
           1       0.89      0.81      0.85        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

   micro avg       0.98      0.98      0.98       519
   macro avg       0.96      0.94      0.95       519
weighted avg       0.98      0.98      0.98       519

Accuracy of the model: 0.9845857418111753


In [32]:
#predicting using the Gradient_Boosting_Classifier

from sklearn.ensemble import GradientBoostingClassifier

model_gb= GradientBoostingClassifier(n_estimators=100,random_state=10)

#fit the model on the data and predict the calues

model_gb = model_gb.fit(X_train,Y_train)

Y_test = model_gb.predict(X_test)

In [33]:
#evaluate the model

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")


print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[100   0   0   0]
 [  3  18   0   0]
 [  0   0 371   0]
 [  2   1   0  24]]
Classification report: 
              precision    recall  f1-score   support

           0       0.95      1.00      0.98       100
           1       0.95      0.86      0.90        21
           2       1.00      1.00      1.00       371
           3       1.00      0.89      0.94        27

   micro avg       0.99      0.99      0.99       519
   macro avg       0.97      0.94      0.95       519
weighted avg       0.99      0.99      0.99       519

Accuracy of the model:  0.9884393063583815


In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier

 

# create the sub models
estimators = []
#model1 = LogisticRegression()
#estimators.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf", C=70,gamma=0.1)
estimators.append(('svm', model3))
#model4 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
#estimators.append(('knn', model4))


# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

In [31]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print('Classification report')

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print('Accuracy of the model:',acc)

[[102   0   0   0]
 [  2  19   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
Classification report
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       102
           1       1.00      0.90      0.95        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

   micro avg       0.99      0.99      0.99       519
   macro avg       0.99      0.97      0.98       519
weighted avg       0.99      0.99      0.99       519

Accuracy of the model: 0.9942196531791907
